name: Playwright - Chrome Form Sender
on:
  workflow_dispatch:

jobs:
  test-page:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Playwright script
        run: node index.js

      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v3
        with:
          name: hepsiburada-screenshot
          path: hepsiburada_test_*.png
