name: Playwright-core + System Chromium
on:
  workflow_dispatch:

jobs:
  test-page:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Ensure Google Chrome is installed (system)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg ca-certificates
          # Install Google Chrome stable if not present
          if ! command -v google-chrome-stable &> /dev/null && ! command -v chromium-browser &> /dev/null && ! command -v chromium &> /dev/null; then
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
          else
            echo "Chrome/Chromium already present"
          fi

      - name: Install npm dependencies
        run: npm ci

      - name: Run playwright-core script (use system chrome)
        env:
          HEADLESS: ${{ secrets.HEADLESS || 'true' }}
        run: node index.js

      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshot_*.png
