name: Playwright-core + System Chromium
on:
  workflow_dispatch:

jobs:
  test-page:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # 1️⃣ Repo'yu checkout et (git push için token ekliyoruz)
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Gerekli: push yapabilmek için

      # 2️⃣ Node.js kur
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Npm cache kullan
      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4️⃣ Lockfile güncelle ve commit/push (otomatik)
      - name: Ensure lockfile is up to date and commit
        run: |
          npm install
          if ! git diff --exit-code package-lock.json; then
            echo "Lockfile updated. Committing changes..."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore: update package-lock.json from workflow"
            git push
          else
            echo "Lockfile is already up to date."
          fi

      # 5️⃣ Deterministik kurulum
      - name: Install npm dependencies
        run: npm ci

      # 6️⃣ Sistem Chrome kur
      - name: Ensure Google Chrome is installed (system)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg ca-certificates
          if ! command -v google-chrome-stable &> /dev/null && ! command -v chromium-browser &> /dev/null && ! command -v chromium &> /dev/null; then
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
          else
            echo "Chrome/Chromium already present"
          fi

      # 7️⃣ Playwright script çalıştır
      - name: Run playwright-core script (use system chrome)
        env:
          HEADLESS: ${{ secrets.HEADLESS || 'true' }}
        run: node index.js

      # 8️⃣ Screenshot artifact olarak yükle
      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshot_*.png
