name: Hepsiburada Login Automation

on:
  workflow_dispatch:
    inputs:
      email:
        description: "İşlem yapılacak e-posta adresi"
        required: true
        type: string

jobs:
  run-login:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node.js kurulum
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Paketleri yükle
        run: npm install

      - name: Login işlemini çalıştır
        id: login
        run: |
          echo "İşlem başlıyor..."
          node index.js ${{ inputs.email }} > output.log 2>&1
          echo "✅ İşlem tamamlandı"

      - name: Log’u kaydet (artifact)
        uses: actions/upload-artifact@v3
        with:
          name: login-result
          path: output.log
